---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Handbrake --version
      ansible.builtin.command: handbrake --help --json
      register: resultout
      changed_when: resultout is not succeeded

    - debug:
        msg: "{{ resultout.stdout }}"
